### ISSUE TITLE
time field in json file

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#1]
When you update imap_hdr.py, also save the email received time as one of the fields into the json file. The time should be stored in UTC format in json file. You can use Date mail header field to extract the time of email generation. An example 

Date: Tue, 22 Dec 2015 17:34:03 +0530
You have to add another line after line#74 of imap_hdr.py; a typical line could be 

data['Time'] = dateToUTC(original['Date'])

The required function needs to be written.

Time field would help generate time-dependent networks later on.

**Comment by achyudh** [comment]
Please check commit 9cabbf7. I request you to close the issue if it has been resolved,

**Comment by prasadtalasila** [comment]
timezone problem solved.
