### ISSUE TITLE
Bipartite graphs

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#10]
A bipartite graph among all the users and messages. All the users (From, To, CC, BCC fields) will be on one side and all the messages will be on another. A directed arrow would be drawn from user to the message sent by the user. A directed arrow would be drawn from message to all the users who are in To, CC and BCC fields.

NetworkX can take this bipartite graph and generate a projected graph of users. A few useful references in this direction are:
https://networkx.github.io/documentation/latest/_modules/networkx/algorithms/bipartite/projection.html  
https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.bipartite.projection.projected_graph.html

**Comment by achyudh** [comment]
I kindly request you to check commit d4cb639.

**Comment by achyudh** [comment]
This module needs to be modified to incorporate recent changes to the code and file organization.

**Comment by achyudh** [comment]
Commit 25f0275 addresses this issue.
