### ISSUE TITLE
Check NetworkX 2.0 compatibility

### ISSUE THREAD

**Issue by achyudh** [prasadtalasila/MailingListParser#104]
Requires.io (https://requires.io/github/prasadtalasila/MailingListParser/requirements/?branch=master) states that our dependencies have become outdated (NetworkX 1.11). I have faced issues when updating to a later version of NetworkX before. In case there are no issues migrating to the newer version, we should do so. 

Checking for NetworkX 2.0 compatibility issues is simple for functions covered by CI tests. We update the NetworkX version in the CI config script and let it run.

**Comment by prasadtalasila** [comment]
There have been problems with directly using NetworkX inside the code. It might be better to refactor the code such that NetworkX is wrapped in an adapter class using [Adapter pattern](https://en.wikipedia.org/wiki/Adapter_pattern). If there is an update in NetworkX, then only the adapter class would change; rest of the code remains the same. If we don't do this, every NetworkX version change requires changes in multiple modules.

**Comment by achyudh** [comment]
@prasadtalasila I agree. But doing such a major refactoring of code would only help if the NetworkX API is changing frequently. That is not the case, and between major versions there are minor changes.

**Comment by prasadtalasila** [comment]
Will be resolved later.
