### ISSUE TITLE
Wrapper python script to run all drivers in order

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#111]
The existing drivers are dependent on each other. It may be better to put a small python / shell script that runs the driver scripts in correct order.

**Comment by achyudh** [comment]
I suggest using a shell script since the other driver files are not in modules, it becomes a mess to call them

**Comment by prasadtalasila** [comment]
@AakankshaSanctis can you send a PR with shell script containing correct order of invocation for the driver python files?

**Comment by hrishikesh-dahiya** [comment]
Would it be helpful to move all the driver files in a separate module since they are not directly run by the user(after the script)?

**Comment by achyudh** [comment]
@hrishikesh-dahiya You might face issues while importing files from the lib folder, and would have to modify a number of paths. Could be done but it is not inside lib so why waste time?

**Comment by achyudh** [comment]
Try this order:
driver_headers_mbox.py	
driver_thread_analysis.py
driver_author_analysis.py

**Comment by hrishikesh-dahiya** [comment]
@achyudhk I just thought that it would give a clean main directory and it would be easy for the user to browse. But if it is not necessary, better not waste time on that then.

**Comment by achyudh** [comment]
@hrishikesh-dahiya What you are saying is true, it is just more refactoring work. If you are fine with that please go ahead.

**Comment by AakankshaSanctis** [comment]
@prasadtalasila ,I have uploaded the pr with the python script to run all the drivers

**Comment by prasadtalasila** [comment]
work completed in PR #112
