### ISSUE TITLE
Update Travis configuration

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#123]
We need to update the travis configuration to support two features.

1. Utilise Travis build cache to reduce Travis build times.
1. Introduce Travis pipelines into the build so that we can run unit and intergration tests in parallel.

**Comment by prasadtalasila** [comment]
We need two pipelines - one for unit tests and one for functional tests. The unit tests pipeline would only have sleep command for 10 seconds.

**Comment by hrishikesh-dahiya** [comment]
PR #135 solves this issue
