### ISSUE TITLE
update templates

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#124]
Copy and suitably modify the following templates.
 
1. PR and Issue templates from [SCAT](https://github.com/DeveloperCAP/SCAT/tree/master/.github).
1. Code of conduct from [autolabcli](https://github.com/AutolabJS/autolabcli/blob/master/CODE_OF_CONDUCT.md)
1. Contributing guidelines from [SCAT](https://github.com/DeveloperCAP/SCAT/blob/master/CONTRIBUTING.md)

All the necessary wiki pages need to be created on MLCAT repository and linked added to the local wiki pages.

**Comment by hrishikesh-dahiya** [comment]
PR #133 resolves this issue
