### ISSUE TITLE
Authors graph for a discussion thread with edge labels

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#13]
For each discussion thread, the graph of authors can be drawn with the following conventions.
1. Subscribers in the **From**, **To**, **CC**, and **BCC** fields become nodes of the graph. 
2. A solid edge is drawn for each email sent **From** node to **To** node. 
3. A dotted edge drawn for each email sent **From** node to **CC** node. 
4. A dashed edge drawn for each email sent **From** node to **CC** node. 
5. The time of transmission of a message is to be put on the edge of the graph.

**Comment by achyudh** [comment]
I kindly request you to check commit d4cb639.  The generation of such a large connected graph as a PNG would be not possible with current resources. However, the analysis of the graph is possible given the various formats NetworkX supports for export.

**Comment by prasadtalasila** [comment]
As per our discussion, one author graph is to be generated for each discussion thread. Apart from the previous graph conventions, the following conventions may help clarify the author communication patterns.
1. Edges colors can depend on the height of the message. Same set of high contrast colors can be reused for coloring the author graph of each discussion thread independently.
2. Each additional time one author refers to another, we can the weight of that respective edge gets incremented by one.

**Comment by achyudh** [comment]
This issue has now been addressed in commit 5975310.
