### ISSUE TITLE
Integration tests for lib/util/read.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#141]
**Description**
Please follow the testing conventions laid out in [py.test tutorial](https://github.com/DeveloperCAP/SCAT/wiki/Pytest-Tutorial)

**Definition of Done**
- [x] Project builds without errors
- [x] Integration tests written and passing
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [x] Peer Code Review performed

**Comment by hrishikesh-dahiya** [comment]
#178 solve this
