### ISSUE TITLE
Create integration tests for modules in lib/util

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#143]
Order of completion:    
 - [x] json_encoder.py 
 - [x] graph.py
 - [x] preprocess.py
 - [x] union_find.py
 - [ ] layout.py

**Comment by hrishikesh-dahiya** [comment]
Add documentation to `test_json_encoder.py`

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya don't add documentation to tests. If something is not very obvious, add a comment. That's about it.

**Comment by prasadtalasila** [comment]
layout.py shall not be tested. The only pending work is PR #170.
