### ISSUE TITLE
Correct the functional test script

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#163]
**Description**
In the [pytest.sh](https://github.com/DeveloperCAP/MLCAT/blob/development/etc/pytest.sh), the shell script needs to have `set -ex` between lines 2 and 3. Without the `set -ex` option, the travis build succeeds even if the pytest (line-14) command fails.

For an example, please see [a build log](https://travis-ci.org/DeveloperCAP/MLCAT/jobs/355098374#L570). Even with a failed test, the build completed successfully.

**Definition of Done**
- [x] Project builds without errors
- [x] Unit tests written and passing
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [x] Peer Code Review performed

**Comment by hrishikesh-dahiya** [comment]
#165 fixes it
