### ISSUE TITLE
Conversation group size

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#17]
The number of participants (authors) taking part in a conversation is can be deduced from a two column table.
![image](https://cloud.githubusercontent.com/assets/9206466/12742470/0f3634a6-c9ac-11e5-949a-9968d284357a.png)

**Comment by achyudh** [comment]
I kindly request you to check commit d4cb639. 
The data/graphs/csv folder contains the required table as a CSV file. The table can be interpreted as follows: The first row (1,4995) implies that 4995 authors have participated in a thread with just one node (i.e. no replies), the second row (2,4983) implies that 4983 authors have participated in a thread with two nodes and so on.

**Comment by achyudh** [comment]
The formatting of the participant-size graph has changed to reflect the average number of authors in a thread.
![image](https://cloud.githubusercontent.com/assets/7617287/12874041/482868c0-cdf2-11e5-90dc-56c76271609d.png)
The first row (1, 4995, 4995, 1) implies that 4995 authors have participated in a thread with just one node (i.e. no replies), there are 4995 such threads and hence an average of 1 author per thread (which makes sense). Similarly,  (2, 2706, 4983, 1.841) implies that 4983 authors have participated in a thread with just 2 nodes, there are 2706 such threads and hence an average of 1.841 authors per thread.
