### ISSUE TITLE
[Test] Integration testing in lib/input/check_headers.py

### ISSUE THREAD

**Issue by tejalwakchoure** [prasadtalasila/MailingListParser#177]
**Description**
Solving the issues regarding code coverage due to patching in check_headers.py

**Definition of Done**
- [ ] Project builds without errors
- [ ] Unit tests written and passing
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by hrishikesh-dahiya** [comment]
#180  solves this
