### ISSUE TITLE
Summary on community detection

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#18]
A working summary of community detection algorithms, specifically Louvain and Infomaps

**Comment by achyudh** [comment]
Please check commit d462d1b regarding the implementation of community detection using Infomaps. As discussed, Louvain would not be best suited for this graph due to its directed nature.

**Comment by achyudh** [comment]
Changes to the code need to be made to use the mapequation.org source for multilevel community detection with Infomap. Then the data from the .MAP file must be used to generate a visual map in the Map Generator.

**Comment by achyudh** [comment]
This issue has been addressed in commit ea7f4e2.
