### ISSUE TITLE
Motifs from graph-tool

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#19]
The motifs generated from graph-tool should either confirm or negate the statistical conclusions from the discussion width-height table.

**Comment by achyudh** [comment]
Graph-tool's clustering module (Refer: https://graph-tool.skewed.de/static/doc/clustering.html#graph_tool.clustering.motifs) don't take into consideration the weights of the graph. Hence the analysis would have to be done on a directed non-weighted graph. Please let me know if I should still proceed.

**Comment by prasadtalasila** [comment]
The motif data on the unweighted graph would still be interesting. Also run the motif_significance function mentioned on the same html page. For each motif, the function returns z-score which would be qualitatively important.

**Comment by achyudh** [comment]
Commit 07ec072 partly addresses this issue, but the detection of motifs of any size is taking an extremely long time resulting in no output.

**Comment by achyudh** [comment]
The graph can be optimized by removing lone author threads and further by removing the stray nodes that are not a part of the single largest strongly connected component (if it exists). The algorithm must then be run for both the thread graph and the author interaction graph.

**Comment by achyudh** [comment]
Further optimizations did not yield any result as the detection of motifs of any size is taking an extremely long time resulting in no output.
