### ISSUE TITLE
Problems in development branch

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#2]
The following issues have been observed in the latest commit of the latest commit on development branch (9cabbf7).

1) The Message-ID in  headers.json and clean_data.json starts at 2001. This is supposed to start at 0.
2) cross-checking of synchronization between Gmail Inbox and *.json files (json files should only be appended).
3) fetch_headers.py missing.
4) proposed structure for code base
    code/
    data/json
   data/graphs

**Comment by prasadtalasila** [comment]
directory structure added to the repository

**Comment by achyudh** [comment]
Please check if commit d8d090d addresses points (2) and (3) of this issue. If this is not the case I request you to elaborate.

**Comment by achyudh** [comment]
Please check if commit 7aaa737 addresses points (1) and (4). If yes, I request you to close this issue. I feel that code could preferably be stored in the root directory of the repo. Directory structure for data is suitable to the project's workflow.

**Comment by prasadtalasila** [comment]
A few issues are still remaining.
1) python script files must move to "code/" and the scripts must be updated to reflect the new directory structure.
2) json files in the top directory can be deleted
    headers.json and clean_headers.json
3) move threadPaths.txt to right location (location to be decided by you)
4) thread_graph_nx.py already in code/util; hence can be deleted from top directory

Thanks

**Comment by achyudh** [comment]
Commit c8d0a3a takes care of issues 1, 2, and 4. As of now "threadPaths.txt" has not been generated for the latest data. As soon as its role in the project is determined, I plan on updating the file. Also, I think the name is very deceptive as this file is supposed to contain the leaf nodes of the discussion thread graphs.

**Comment by prasadtalasila** [comment]
development branched merged into master

**Comment by prasadtalasila** [comment]
The file paths in python scripts need to be updated. See http://stackoverflow.com/questions/918154/relative-paths-in-python
for a way of writing portable code

**Comment by achyudh** [comment]
Please consider the fact that changing the file paths beats the purpose of separating data from the actual code. An unwanted call to any of the functions can change or rewrite the JSON files for the worse and would consume our time in an unwanted manner. I the past I had to repeatedly use Git revert and in cases where I had uncommitted changes, I had to undo this operation manually by hand.
