### ISSUE TITLE
Decaying factor for a relationship

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#20]
So far we have been trying to create relationships between authors who send email messages to each other. It may also be true that authors who are not in touch with each other would lose their relationship.

What is a systematic approach to determining the decaying factor for a relationship? In common terms, how much of time would elapse before two neighboring subscribers become strangers to each other?

**Comment by prasadtalasila** [comment]
We can approach this question by slightly changing the code that generates the LKML author graph.

We can maintain a list for each edge seen so far (let's focus only on From-To edges). The first time an edge is created between two authors, its' creation time is noted down. The next time this edge is seen again, the time difference, i.e. Tedge2 - Tedge1, becomes the refresh time interval for this edge. The refresh time intervals are recorded in another list. Each edge in the edge list shall have the latest edge refresh time in order to enable the computation of the edge refresh time intervals for any one of the edges.

At the end, we have a list of refresh time intervals. The statistical distribution of this list tells us about the nature of the refresh interval. Once we have this answer, we can empirically answer the decaying constant question.

**Comment by achyudh** [comment]
Commit 62edd11 addresses this issue.
