### ISSUE TITLE
Hyperedge representation

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#21]
We can model each discussion thread as one hypergraph. All the email header information can be represented as one hyperedge of a hypergraph. A conscise format for representing a discussion thread is as follows.

![image](https://cloud.githubusercontent.com/assets/9206466/13031082/15d7b61c-d2e5-11e5-971f-ce0f44a4a755.png)

Here the author column headers would contain the ids of the authors. All the author columns are to be sorted left to right in the descending order of out degree, followed by in degree.

An example table for the discussion thread number 5141 is as follows.
![image](https://cloud.githubusercontent.com/assets/9206466/13031097/66961c2e-d2e5-11e5-97a3-6a8cd959c357.png)

The authors identified in this discussion thread are indexed in a separate file. A sample file just for the discussion thread number 5141 would be as follows

![image](https://cloud.githubusercontent.com/assets/9206466/13031117/0abf5edc-d2e6-11e5-8c09-16ae1828d0b7.png)

The author identifiers file can also be created in json format.

**Comment by achyudh** [comment]
Please refer to commit 5aa5b65. This issue has now been addressed.
