### ISSUE TITLE
Graphs from json files

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#3]
The graphs to be generated from json files in three different formats, namely GEXF, dot format and png files. These files can be saved in the directory structure at the following places.
   data/graphs/gexf
   data/graphs/dot
  data/graphs/png

Each graph file can be named with the Message-ID of the starting mail of the discussion thread.

**Comment by achyudh** [comment]
This issue has now been addressed. Please refer commit commit 0be7a26.
