### ISSUE TITLE
Distribution Hub Network

### ISSUE THREAD

**Issue by achyudh** [prasadtalasila/MailingListParser#33]
Distribution hubs like linux-kernel@vger.kernel.org can be distinguished by the fact that they would have no out-degree. Hence it is possible to analyze the network formed by just the distribution hubs. Howver, the distribution hubs need to be verified manually so as not to remove people with high out-degree/in-degree ratio like linus@linux-foundation.org.

For the real social network created by the users, we need to remove the distribution hubs. An email sent to a distribution hub goes to everyone, so there is no real targeted interaction there. We can look at the social network and the communities after removing the distribution hubs. It would be interesting to see if there are multilevel communities in the induced network. The library version of Infomaps can provide details of multi-level communities and can produce a .tree file.

**Comment by prasadtalasila** [comment]
Not a priority now.
