### ISSUE TITLE
Analysis Framework Outline

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#36]
- [x] Channel profile -- heatmap and conversation characteristics
- [ ] Network profile -- presence and message exchange social networks, network analysis, hyperedges, thread-level analysis
- [x] User profile -- author participation, user ranking (from degree differential), keyword digest
- [x] New items -- thread-level analysis (network profile), author participation (user profile), hyperedges
- [x] Removed items -- nick tracking (user profile)

**Comment by achyudh** [comment]
The heatmaps part of channel profile analysis has been addressed in commit 365262a.

**Comment by achyudh** [comment]
Presence networks removed from analysis for now.
