### ISSUE TITLE
Separate Pre-release Branch

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#42]
It would be a good practice to have a ready release / pre-release for the software. That way, any foreseen issues on the dev branch would not effect the people who would want to use the software.

We can have a working commit that is decent, create a release out of it.

**Comment by achyudh** [comment]
I have been using the master branch for the purpose. All commits are done on the dev branch by default. I only merge dev to master after every few incremental updates if the Travis tests pass. Please let me know if this is the correct approach.

Can't we create snapshots like the SNAA_snapshot for other needs?

**Comment by prasadtalasila** [comment]
The idea seems okay. We can have a release on a tagged commit using github releases approach. Once we have ready made code for a publication, we can have that release on master or separate branch, based on the amount of customizations required for the publication.

Once a working release is in place, this issue can be closed.

**Comment by achyudh** [comment]
Commit 3ed2e2a is Release v0.10
