### ISSUE TITLE
Generate Call Graphs

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#45]
snakefood [usage](https://gist.github.com/prasadtalasila/deb3e55d8f084ba375d1c31712e1c7e4)    

pycallgraph [usage](https://gist.github.com/prasadtalasila/71893b1eb8dfc425fba169b4c70b1475)

**Comment by hardik124** [comment]
@prasadtalasila , Is this issue still relevant?

**Comment by achyudh** [comment]
@hardik124 Every unclosed issue is relevant as we regularly update these.

**Comment by hardik124** [comment]
@achyudhk  I would like to work on it. Could you please provide some more details?

**Comment by prasadtalasila** [comment]
@hardik124 We would like to see the dependency diagram (alias call graph) to understand the critical aspects of the application. Having an understandable call graph would be a first step towards prioritizing the work towards areas of code which if improved can provide maximum benefit.

There are already links to sample usage of these programs. You can run these programs for typical scenarios of invocation for the MailingListParser application and get the call graphs out.

**Comment by hardik124** [comment]
@prasadtalasila ,
Call graph for the whole project can be generated by snake food.
Should  I add a bash script to generate?

**Comment by prasadtalasila** [comment]
@hardik124  Please generate the call graph for the whole project and link it here. Based on the generated graph, we can take the work forward.

**Comment by hardik124** [comment]
@prasadtalasila  These are the call graphs generated by Snake food. Please check if its alright.
[call-graphs.zip](https://github.com/prasadtalasila/MailingListParser/files/1394288/call-graphs.zip)

Please note, the file name is in format, -{dir}-{subdir}-{subdir}...{filename of python script}.pdf

**Comment by achyudh** [comment]
I'm familiar with the codebase and I can check this for you. However, when I try to open the PDF files it says invalid header.

**Comment by hardik124** [comment]
Hey @achyudhk  . It was opening in Ubuntu. I was not sure which format snakefood converts in.
I think you need graphwiz to view them.

**Comment by achyudh** [comment]
I tried opening it with multiple PDF readers and it said the document was corrupted. I assumed 

I will try the Ubuntu l's default PDF reader EVINCE later on. I suggest you fix the extension in case it's incorrect

**Comment by hardik124** [comment]
@achyudhk . I got the problem. It converts it into graphviz dot file. 
I used ps2pdf to convert them to pdf. Can you verify if these pdfs are working?
[CallGraphs.zip](https://github.com/prasadtalasila/MailingListParser/files/1394335/CallGraphs.zip)

**Comment by achyudh** [comment]
@hardik124 I ran file identification on your file and apparently it is a PostScript document text conforming DSC level 3.0. Even though some PDF viewer may open it it technically is a PS or EPS file. I suggest you output PDFs from now as it's easy for everyone to view and has integrated support in Github to view without downloading.

**Comment by hardik124** [comment]
@achyudhk  please check my previous comment.

**Comment by achyudh** [comment]
In Graphviz you can directly save as PDF rather than relying on external tools. I'll verify them now. 

DOT files are text and what you submitted was binary. Please note the difference.

**Comment by achyudh** [comment]
You seem to be running it on init files, conf.py and even text files resulting in blank call graphs. I suggest you don't run on those files. 

More importantly:
What you are doing great doesn't look the call graphs to me. This is only of single level, and has only file names and not actual function names. This is useful though in the sense we can identify cohesion and coupling in the codebase but this will not help us identifying bottlenecks which was the reason we wanted to generate call graphs. I request @prasadtalasila also to take a look

**Comment by hardik124** [comment]
@achyudhk  I used ran the command "sfood {file} | sfood-graph | dot -Tps >> {.output} on all of the .py files to generate these as snakefood documentation said.

**Comment by achyudh** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/2/2f/A_Call_Graph_generated_by_pycallgraph.png)

This is what a call graphs is supposed to look like. I'm sure you can fiddle with the utility to get this.

**Comment by hardik124** [comment]
@achyudhk . In this particular example, They ran the code and generated the call graph through that. Is that what I have to do?

**Comment by hardik124** [comment]
@achyudhk . Actually, I realized my mistake now. Snakefood is generating a dependcy graph. I will try for call graph.

**Comment by hardik124** [comment]
![out](https://user-images.githubusercontent.com/6649948/31758106-b27c415a-b4c9-11e7-83aa-3da3d2ea47a7.png)
@achyudhk @prasadtalasila  Please check if this is right.

**Comment by hardik124** [comment]
@achyudhk  Please check if this call graph is right, so that I can generate for all others

**Comment by achyudh** [comment]
@hardik124 It takes me a while sometimes to respond. I hope that won't be an issue with you.

You have chosen read utils as a sample class for generating a call graph, but the issue is the functions in utils module barely make any function calls as their purpose is to *assist other modules*. This seems to be correct but if you can do this for one of the driver files I can provide proper feedback

**Comment by achyudh** [comment]
Also your graph has the function name but no information on the module or class to which it belongs. That information is crucial

**Comment by hardik124** [comment]
@achyudhk  None of the driver files in /lib are generating a call graph except for test_driver and that calls the defined in that class itself .
![erd](https://user-images.githubusercontent.com/6649948/31921649-1b230ff0-b88e-11e7-945a-252ded8aa6e6.png)

**Comment by achyudh** [comment]
Check out the files in the driver folder. Those scripts will give you a call graph.
**This one looks nice** but doesn't go inside the modules that is being called. We would like to see the entire call stack. I know drive data handling has a function that calls so many other functions from the other modules in the project. We would like to see those too. See if you can increase the depth of the tree somewhere.

**Comment by hardik124** [comment]
@achyudhk  i am unable to find the driver folder you are talking about. Can you please give complete path?

**Comment by prasadtalasila** [comment]
@hardik124 you can check the filenames starting with driver_* in [dev branch](https://github.com/prasadtalasila/MailingListParser/tree/development)

**Comment by prasadtalasila** [comment]
Not a priority right now.
