### ISSUE TITLE
Transition from Wiki to Sphinx Documentation

### ISSUE THREAD

**Issue by achyudh** [prasadtalasila/MailingListParser#48]
- [x] Setup basic Sphinx documentation support with website
- [x] Enable and theme the documentation website
- [x] Copy information from Wiki to documentation
- [x] Update README with links to documentation and better project overview

**Comment by achyudh** [comment]
Dear @prasadtalasila, I kindly request you to do the following to enable the doc website:

> Click on the Settings tab and scroll down to the GitHub Pages section. 
> Then select the gh_pages branch source and click on the Save button.

I need to be able to see the website to figure out how it works and set it up.

**Comment by prasadtalasila** [comment]
pending work.

1. Copy https://github.com/prasadtalasila/MailingListParser/wiki/Overview-of-Project-Modules
2. Create a matching page for https://github.com/prasadtalasila/MailingListParser/wiki/Algorithm-Documentation under **Contents** with the section header of "Algorithm for parsing of Mailinglists."
