### ISSUE TITLE
uid cross checks in imap_hdr.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#5]
The following issues exist with get_mail_header() method.
1) method still fetching from to_get[0] to \* (line#92 of imap_hdr.py).  
2) In case get_mail_header() gets called with future uid numbers, the method should indicate last valid uid and stop the work. Right now, the loop is unnecessarily running inside the method.  
3) You have plans to delete invalid data; these deleted mail entries show up as missing uids next time, get fetched and get deleted again. It may be useful to keep a list of deleted uids so that these need not be fetched repeatedly.

This rewrite is not a priority. It can wait till code review at the beginning of next semester.

**Comment by achyudh** [comment]
All three issues have been resolved in commit ddc4c2e. Please check the commit message for more details. I am closing this issue. Please reopen it in case anything more is required.
