### ISSUE TITLE
Generation of Test Cases

### ISSUE THREAD

**Issue by achyudh** [prasadtalasila/MailingListParser#52]
- [ ] Fill up the TODO stubs of the tests for author analysis and thread analysis

- [ ]  Refactor tests to mirror the module structure of the project

- [ ] Set up a unit testing framework

**Comment by achyudh** [comment]
Unit tests are actually crucial to verify the correctness of our results. I hope someone would work on the initial framework I had already setup for this.

**Comment by prasadtalasila** [comment]
@yashpungaliya will get started on unit tests as soon as the present work in the [worksheet](https://github.com/prasadtalasila/MailingListParser/projects/1) is complete.

**Comment by achyudh** [comment]
That would be great and I will also join in during that phase. The integration tests are already in place and they don't tell us about the correctness of the code we are pushing.

**Comment by achyudh** [comment]
@hrishikesh-dahiya Please take a look at this.

**Comment by hrishikesh-dahiya** [comment]
What is the current framework setup for unit testing?

**Comment by achyudh** [comment]
Check out: https://docs.pytest.org/en/latest/
Find a basic integration test for all the modules here: https://github.com/prasadtalasila/MailingListParser/blob/master/lib/test_integration.py

**Comment by prasadtalasila** [comment]
There is an [all-in-one help document](https://media.readthedocs.org/pdf/pytest/latest/pytest.pdf) as well. If everything that's promised in the document works, then we can happily use pytest for all kinds of testing in the project. 

The [plug-in](http://plugincompat.herokuapp.com/) system seems good as well.

**Comment by prasadtalasila** [comment]
Progress on testing would be tracked through creation of smaller issues.
