### ISSUE TITLE
Auto-generating the documentation for master branch

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#57]
Each time master branch is updated, Travis script must generate the HTML documentation from sphinx documentation

**Comment by achyudh** [comment]
Solved in PR: Add support for doc autogen #65
Travis environment variables need to be updated with your personal access token for this to work

**Comment by prasadtalasila** [comment]
@achyudhk The line-72 of etc/deploy_docs.sh script is pointing to your fork. That needs to be updated. 

Also please enumerate the names of the environment variables so that I can match with the names on travis-ci.org. Right now, I see one variable named GH_TOKEN. Is that it or are there any other variables? Thanks.

**Comment by achyudh** [comment]
That is the only variable. I am thinking of adding the repo address as a
variable also as we would face issues every time we are merging anything
from my fork or someone else branches from your repo. I would like your comments on that.

Yours,
Achyudh Ram

**Comment by prasadtalasila** [comment]
sounds good. I will add the the GH_TOKEN to the travis.

**Comment by achyudh** [comment]
Thanks for your quick response. I request you to add REPO_NAME to Travis too with the value: prasadtalasila/MailingListParser.git

Right now the address is mentioned as:
https://${GH_TOKEN}@github.com/achyudhk/Mailing-List-Network-Analyzer.git

**Comment by achyudh** [comment]
I will modify the script to reflect the change accordingly as:
https://${GH_TOKEN}@github.com/$(REPO_NAME)

**Comment by prasadtalasila** [comment]
Both the tokens have been added to travis-ci settings.

**Comment by achyudh** [comment]
That's great. Can you please also ensure that GH-Pages is the branch from which we are publishing the documentation? That all that we need to get this working.

Thanks a lot.

**Comment by prasadtalasila** [comment]
The website is being served from gh-pages branch. Yash pushed a few manual commits on to the branch and got them visible on the website. Good work.

**Comment by achyudh** [comment]
The changes have been merged and this has been verified working. Thanks a lot for your help.
