### ISSUE TITLE
error in builds due to deploy_docs.sh

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#73]
The [document auto generation script](https://github.com/prasadtalasila/MailingListParser/blob/development/etc/deploy_docs.sh) fails on any branch other than master or deployment. For a sample scenario, please see the travis [build log](https://travis-ci.org/prasadtalasila/MailingListParser/builds/277751758) of 21d41e1 commit made on [install](https://github.com/prasadtalasila/MailingListParser/tree/install) branch.

**Comment by achyudh** [comment]
The build seems to fail if there is nothing to commit to the documentation. This is just a hunch. We have to check if the documentation has in fact changed in the deploy_docs.sh script before attempting to make a commit.

`Your branch is up-to-date with 'origin/gh-pages'.
nothing to commit, working tree clean
The command "bash etc/deploy_docs.sh" exited with 1.`

**Comment by achyudh** [comment]
Another question I would like to think about is do we need to generate and deploy the documentation for all commits in all branches? It makes sense to restrict this to updates in the master branch.

**Comment by prasadtalasila** [comment]
It makes sense to restrict documentation generation to development branch. For a way to do this, please see [lines 22 to 25](https://github.com/prasadtalasila/IRCLogParser/blob/dev/ext/doc_auto_deploy.sh#L22-L25) of sample script.

The problem of successfully bailing out in case of no git commit is also addressed in [lines 51-55](https://github.com/prasadtalasila/IRCLogParser/blob/dev/ext/doc_auto_deploy.sh#L51-L55) of the same sample script.

**Comment by achyudh** [comment]
I have made both the changes in my repository. I am currently testing them. I will let you know if that was the cause.

**Comment by achyudh** [comment]
This issue has been fixed n https://github.com/prasadtalasila/MailingListParser/pull/74
