### ISSUE TITLE
streamlining of branches

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#77]
The following branches seems to have served their purpose.

* [revert-71-development](https://github.com/prasadtalasila/MailingListParser/tree/revert-71-development)
* [revert-64-master](https://github.com/prasadtalasila/MailingListParser/tree/revert-64-master)
* [snaa_snapshot](https://github.com/prasadtalasila/MailingListParser/tree/snaa_snapshot)

Also the development branch is completely out of touch with the master branch. If there is nothing extra in the master branch, let the master branch HEAD move to the HEAD of the development branch.

Please let the [java_deprecated](https://github.com/prasadtalasila/MailingListParser/tree/java_deprecated) branch remain in place for now. The branch has historic value.

**Comment by achyudh** [comment]
I was thinking we could sync the dev and master branches once we remove the unnecessary data files. I shall remove the reverted branches and the snapshot.

**Comment by achyudh** [comment]
Issue #88 is addresses the same issue. I am closing this for now.
