### ISSUE TITLE
Color coding graphs

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#8]
There is some advantage to color coding the graph vertices based on the author. The motivation is to see the number of people participating in the thread. A set of standard colors can be picked for assignment and the set can be used across all threads.

All authors of a thread are identified and each author is given a unique color. All messages sent by this author get the same color. In the graphs, the color distinction can be made by changing the color of the oval node line.

**Comment by achyudh** [comment]
Graphs have now been color coded based on a set of contrasting colors. The commit currently being pushed would solve this issue.
