### ISSUE TITLE
Run mbox of sakai-devel through code base

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#82]
In #81, we consider the processing of lkml mbox. In this issue, we consider the processing of sakai-devel mbox.

**Comment by yashpungaliya** [comment]
Sir,
Can you please put the mbox for sakai and lkml on the server, I don't have
them.
Thanks,

Yash Pungaliya.

**Comment by prasadtalasila** [comment]
see #95.
