### ISSUE TITLE
Fix script to generate graphs

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#85]
The etc/generate_graphs.sh is broken. Need to fix it in order to automatically generate graphs.

**Comment by achyudh** [comment]
The driver files were developed to phase out these shell scripts. That script is too old now and can be removed. During one of our meetings, @prasadtalasila and I decided that plotting graphs is not practical and this led to the development analysis driver files that perform all the analyses without actually plotting and saving every graph.

**Comment by prasadtalasila** [comment]
@achyudhk please list the scripts that are redundant so that @yashpungaliya can remove the same.

**Comment by yashpungaliya** [comment]
@achyudhk The analysis of author and thread runs successfully on the server.However,before moving to the Shrunk repository we need a way to reproduce all pre-existing results so that they can be regenerated automatically later with any data. Can you please suggest how to go about it?

**Comment by achyudh** [comment]
@yashpungaliya I am not sure if I understand your question. If you provide the correct paths to the files in the driver, it can technically run on any MBOX file.

**Comment by achyudh** [comment]
@prasadtalasila @yashpungaliya 

As far as I could see these are the deprecated scripts:

https://github.com/prasadtalasila/MailingListParser/blob/master/etc/create_directory_structure.sh

https://github.com/prasadtalasila/MailingListParser/blob/master/etc/generate_graphs.sh

Restructuring the data folders (into input and output) will affect this script but it is still useful:
https://github.com/prasadtalasila/MailingListParser/blob/master/etc/organize_mbox_files.sh

**Comment by achyudh** [comment]
@yashpungaliya Can I close this issue after removing these files?

**Comment by prasadtalasila** [comment]
@achyudhk please feel free to delete the unnecessary files.

**Comment by achyudh** [comment]
I have removed the scripts. Also @yashpungaliya regarding your query:
- The hierarchical clustering dendrograms and the vertex clustering graphs were generated manually with R. There doesn't exist a script for that
- Heatmaps were replaced with timeline graphs. Please confirm with @prasadtalasila if heatmaps are still used in the analysis. If yes, the relevant code is still present.

**Comment by prasadtalasila** [comment]
The heat maps code can remain deprecated for now.

I also created issue #86 to help track the code missing issue. ~~If the unnecessary shell scripts are deleted, we can close this issue.~~

My bad. @achyudhk already closed the issue.
