### ISSUE TITLE
synchronize master and dev branches

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#88]
The master and development branches have significant differences. We need to prepare the development branch for PR onto master branch.

Please prepare the development branch and open a PR. We need to make sure that the deleted files do not make their way into the master branch through this merge PR.

**Comment by prasadtalasila** [comment]
Also the `achyudhk-vertex-clustering` and `vertex_clustering_temp` seemed to have served their purpose. @achyudhk you can take a call on `achyudhk-vertex-clustering` and @yashpungaliya on `vertex_clustering_temp`. Please remove them if they are no longer necessary.

**Comment by achyudh** [comment]
Both of them are no longer necessary. I have removed them.

**Comment by prasadtalasila** [comment]
@achyudhk Thanks.
