### ISSUE TITLE
width-height table

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#9]
Generation of 
![width-height-table](https://cloud.githubusercontent.com/assets/9206466/12263189/231c117a-b953-11e5-9486-fed468e06400.png)

This table provides an aggregate statistical view of all the discussion threads. The number of children is the maximum number of children in any generation of a discussion thread.

This table generation can be automated by counting the maximum number of a certain rank in a discussion thread. The table itself can be temporarily stored in a two dimensional array.

**Comment by achyudh** [comment]
I kindly request you to check commit 8a703f7 regarding the generation of this table. The data/graphs/csv folder contains one version of the width-height table.

**Comment by prasadtalasila** [comment]
Good work
