### ISSUE TITLE
Implementation of config dictionary object driver 

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#91]

**Comment by achyudh** [comment]
Double backslashes are due to r, raw string. It is used because the \ might escape some of the characters. It is usually good practice to do this.

**Comment by prasadtalasila** [comment]
@yashpungaliya please provide an example of the problem you are highlighting in this issue.

Any required directory paths should be passed in as parameters to methods (functions). It is not a good practice to hard code the directory paths in the code. We may need to use a configuration file which gets available as a config dictionary object driver file. The driver file can pass the necessary configuration as argument to the methods (functions).

**Comment by achyudh** [comment]
@prasadtalasila The directory paths are not hard-coded in most of the active code (maybe in some deprecated modules). The methods usually take the directory as an argument. However, if the path is not provided they have a fallback path which is hard-coded.

There aren't any problems with the directory paths. Yash is just pointing out that we aren't following a best practice.

**Comment by achyudh** [comment]
A config dictionary is a good idea. Right now the drive files generate the paths dynamically based on the mailing list in consideration. This can be moved to a PathConfig class and rather than passing all paths as parameters, we can pass just one PathConfig class. Please let me know what you think

**Comment by prasadtalasila** [comment]
The config object idea is worth implementing. Here a config object can be more general than a path configuration. There seem to be two approaches we can use for dictionary object which will have all the config.

* Pass the dictionary object to any function that wants configuration.
    * function would take what is necessary from this dictionary.
    * nothing prevents a function from taking anything else

* Pass the minimal required config dictionary.
    * create a small required config dictionary as a return value of one of methods of config object
    * reduces coupling significantly, but more work in config object.

@achyudhk  @yashpungaliya Please pitch in with your ideas.

**Comment by achyudh** [comment]
A hybrid of what you suggested, Lazy evaluation of the config parameters. We pass the minimal information as fields in the dictionary when the config obj is created. The other fields when required are dynamically computed from the minimal information already present. This prevents having a bloated object with all parameters already filled and helps in quick creation of the object.

**Comment by achyudh** [comment]
@prasadtalasila Any comments on my suggestion above? With all the other issues cropping up due to wrong paths this is sorely needed.

**Comment by prasadtalasila** [comment]
I am in favor of creating a minimal config object parameter approach. Any function that requires configuration gets just enough configuration information via config object. The config object itself is created from ConfigCreator class which is implemented using Abstract Factory design pattern.

**Comment by achyudh** [comment]
@prasadtalasila In that case I will try to create a prototype config object and send it for review as soon as I find sometime. Thanks for your suggestion. 

We can also include methods to create other commonly accessed config options from the minimal config. I feel this would reduce code duplication.

**Comment by prasadtalasila** [comment]
Python has in-built [ConfigParser](https://docs.python.org/3/library/configparser.html) class we can reuse and extend.

**Comment by prasadtalasila** [comment]
A good tutorial on different config options is [here](https://martin-thoma.com/configuration-files-in-python/)

**Comment by prasadtalasila** [comment]
@AakankshaSanctis 
The pending work on this issue is:
1. Sphinx documentation for [config.py](https://github.com/DeveloperCAP/MLCAT/blob/development/lib/mlcatconfig/config.py)
1. Improve test coverage / remove redundant tests in [test_config.py](https://github.com/DeveloperCAP/MLCAT/blob/development/test/unit/lib/config/test_config.py) 
1. Clean up the code coverage for config.py

**Comment by prasadtalasila** [comment]
Not a priority right now.
