### ISSUE TITLE
igraph import error

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#93]
On running the driver_author_analysis.py, igraph gives an import error for igraph.
I have installed graph using 
`pip3 install python-igraph`
which gives-
`ImportError: /home/yash/anaconda3/bin/../lib/libstdc++.so.6: version ``CXXABI_1.3.8'` `not found (required by /home/yash/.local/lib/python3.6/site-packages/igraph/_igraph.cpython-36m-x86_64-linux-gnu.so)
`
How to resolve this? I could not find a solution on stackoverflow.

Also,we need to add this to requirements.txt

**Comment by yashpungaliya** [comment]
@achyudhk Can you help with this?

**Comment by achyudh** [comment]
Try `conda update libgcc` or `conda install libgcc`

You can either update the libgcc package to match your local version, or ensure consistency by installing igraph from within conda and not pip: `conda install -c marufr python-igraph `
