### ISSUE TITLE
Could not generate graph_nodes.csv and graph_edges.csv in driver_headers_mbox.py

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#94]
Error encountered when the entire output is to be regenerated with only the directory structure in data/ and the required mbox file is in place.

`
File "driver_headers_mbox.py", line 28, in <module>
    generate_edge_list(author_nodelist_filename=nodelist_filename, author_edgelist_filename=edgelist_filename,author_json_filename=author_uid_filename)
  File "MailingListParser/lib/analysis/author/edge_list.py", line 53, in generate_edge_list
    lone_author_threads = get_lone_author_threads(None, nodelist_filename, edgelist_filename)
  File "/MailingListParser/lib/util/read.py", line 33, in get_lone_author_threads
    with open(nodelist_filename, "r") as node_file:
FileNotFoundError: [Errno 2] No such file or directory: 'graph_nodes.csv'
`

**Comment by yashpungaliya** [comment]
The modified function call is what I used :  

`generate_edge_list(author_nodelist_filename=nodelist_filename, author_edgelist_filename=edgelist_filename,author_json_filename=author_uid_filename)`

**Comment by achyudh** [comment]
It should not happen. I checked both https://github.com/prasadtalasila/MailingListParser/blob/master/lib/analysis/author/edge_list.py and https://github.com/prasadtalasila/MailingListParser/blob/master/lib/util/read_utils.py.

It looks like either the nodelist_filename you are passing is incorrect or it is not being propagated to the get_lone_author_threads function.  Can you please check if nodelist_filename is of the correct value? It seems to be rolling back to 'graph_nodes.csv' which is the default value in case the nodelist_filename parameter is not being passed.

**Comment by yashpungaliya** [comment]
@achyudhk  I rectified the function call,however I think that the graph_nodes.csv is being accessed by get_lone_author_threads before being written in generate_edge_list

```
File "driver_headers_mbox.py", line 28, in <module>
    generate_edge_list(author_nodelist_filename=nodelist_filename, author_edgelist_filename=edgelist_filename,author_json_filename=author_uid_filename,threads_json_filename=thread_uid_filename)
  File "MailingListParser/lib/analysis/author/edge_list.py", line 54, in generate_edge_list
    lone_author_threads = get_lone_author_threads(None, author_nodelist_filename, author_edgelist_filename)
  File "MailingListParser/lib/util/read.py", line 33, in get_lone_author_threads
    with open(nodelist_filename, "r") as node_file:
FileNotFoundError: [Errno 2] No such file or directory: './data/opensuse-kernel/tables/graph_nodes.csv'

```

**Comment by yashpungaliya** [comment]
generate_edge_list from lib.analysis.thread.graph is a function that writes graph_nodes.csv and graph_edges.csv. Is this is the right way to go about it?

**Comment by achyudh** [comment]
Ideally it's supposed to get the foldername of the dataset and write to graph_nodes.csv in that. That's what I remember doing for most functions.

**Comment by achyudh** [comment]
This is how the function call should be. 

`generate_edge_list("author_nodes.csv", "author_edges.csv", threads_json_filename=headers_filename, nodelist_filename=nodelist_filename, edgelist_filename=edgelist_filename, author_json_filename=author_uid_filename)`

Your function call was wrong. Also regarding your claim that 

> lib.analysis.thread.graph is a function that writes graph_nodes.csv and graph_edges.csv

I don't see an issue. I node_list is basically a by-product of calculating an edge_list and is only used to provide contextual information about the nodes in the edge_list. 

I have verified everything to be working, at least in my fork.
