### ISSUE TITLE
List of Missing, Matching and Additional files-Sakai-Devel

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#95]
The current driver files give output which varies from the data generated earlier in MailingListParser.
I have divided them into 3 categories namely **Missing, Matching** and **Additions.**

### Sakai-Devel mbox
 
**Missing** : 
plots/conversation_chars.png **_code missing_**
plots/conversation_refresh_times_inv.png _**resolved - driver_author import**_
plots/conversation_refresh_times.png _**resolved - driver_author import**_	
tables/conversation_refresh_times.csv _**resolved - driver_author import**_	

**Matching** :
author_keyword_digest.txt
	  conversation_refresh_times.csv
	  curve_fit/*
	  plots/daily-message-activity-timeline.html
	  plots/weekly-message-activity-timeline.html
	  plots/monthly-message-activity-timeline.html
	  plots/yearly-message-activity-timeline.html
	  plots/hyperedge_distribution.png
	  plots/response_time.png
	  plots/response_time_inv.png
	  plots/thread_length.png
	  plots/thread_length_inv.png
	  tables/* (except conversation_refresh_times.csv)

**Additions**:
community_vertex_clustering.txt
	           conversation_refresh_times_inv.png
		   conversation_refresh_times.png
		   json/clean_data.json
		   plots/author_thread_participation.png
		   vc.pdf
		   vd.pdf

**Comment by prasadtalasila** [comment]
moved to [wiki page](https://github.com/DeveloperCAP/MLCAT/wiki/Reproduction-of-Results)
