### ISSUE TITLE
List of Missing, Matching and Additional files-LKML

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#96]
The current driver files give output which varies from the data generated earlier in MailingListParser.
I have divided them into 3 categories namely **Missing, Matching** and **Additions**.
### LKML mbox

**Missing Code**
	   plots/Inter_arrival_times_hist.png **_missing code_**
	   plots/Inter_arrival_times_hist_range.png **_missing code_ **
	   ignore-lat.html **_missing code_**
	   ignore-lat.png **_missing code_**
	   lat.html **_missing code_**
	   lat.png **_missing code_**
	   tables/distribution_hubs.csv _**missing code**_
	   tables/thread_inter_arrival_times.csv _**missing code**_
	   tables/thread_length_distribution.csv _**missing code**_
	   unwanted_uid.txt **_function call in driver_imap_**
	   tables/participant_size_table.csv **_function call missing_**

plots/participant_size_table.png **_missing code_ - csv generated**
	   plots/wh_table_authors.png **_missing code_ - csv generated**
	   plots/wh_table_threads.png **_missing code_ - csv generated**

**Resolved :**
graphs/*
	   plots/author_thread_participation.png  _**resolved - driver_author import**_
	   plots/conversation_refresh_times.png _**resolved - driver_author import**_
plots/author_thread_participation.png  _**resolved - driver_author import**_
	   plots/conversation_refresh_times.png _**resolved - driver_author import**_
	   plots/thread_length_hist.png _**resolved - driver_thread import**_
plots/hyperedge_distribution.png _**resolved - driver_thread import**_
	   heatmaps/* _**resolved - driver_thread import**_
	   keyword_digest_authors.txt **_renamed to author_keyword_digest.txt_**
	   tables/author_thread_participation.csv _**resolved - driver_author import**_
	   tables/author_thread_participation.csv _**resolved - driver_author import**_
	   lone_author_threads.txt _**parameter:False**_
tables/conversation_refresh_times.csv _**resolved - driver_author import**_
tables/hyperedge_distribution.csv _**resolved - driver_author import**_
**Deprecated**
	   plots/degree_dist_hist.png _**deprecated**_   
	   plots/degree_dist_hist.png _**deprecated**_
           infomap/* **_deprecated_**  
           authors_keyword_svd.txt _**deprecated**_ 
	   keyword_digest_clusters_infomap.txt	_**deprecated**_
	   tables/clustering_coefficients.csv _**deprecated**_
	   tables/degree_distribution.csv _**deprecated**_
	   tables/keyword_digest_chi2_scores.csv _**deprecated**_
	   tables/top_authors_data.csv _**deprecated**_

**Matching** :
community_vertex_clustering.txt
tables/author_ranking.csv
tables/wh_table_authors.csv
tables/wh_table_threads.csv
tables/graph_edges.csv
tables/graph_nodes.csv

**Additions**:
author_keyword_digest.txt
		  conversation_refresh_times.csv
		  conversation_refresh_times_inv.png
		  conversation_refresh_times.png
		  curve_fit/*
		  json/*
		  plots/daily-message-activity-timeline.html
		  plots/weekly-message-activity-timeline.html
		  plots/monthly-message-activity-timeline.html
		  plots/yearly-message-activity-timeline.html
		  plots/response_time_inv.png
		  plots/response_time.png
		  plots/thread_length_inv.png
		  plots/thread_length.png
		  tables/response_time.csv
		  tables/conversation_length.csv
		  vc.pdf
		  vd.pdf

**Comment by prasadtalasila** [comment]
please separate the missing category into minor sub-categories of **deprecated**, **resolved**, and **code missing**.

All the function call missing cases can be taken care by adding respective calls to drivers.

**Comment by yashpungaliya** [comment]
@achyudhk Can you please comment regarding missing code section?

**Comment by prasadtalasila** [comment]
moved to [wiki page](https://github.com/DeveloperCAP/MLCAT/wiki/Reproduction-of-Results)
