### ISSUE TITLE
List of Missing, Matching and Additional files-Opensuse-Kernel

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#97]
The current driver files give output which varies from the data generated earlier in MailingListParser.
I have divided them into 3 categories namely **Missing, Matching** and **Additions.**

### Opensuse-Kernel mbox

**Resolved** : 
heatmaps/* _**resolved - driver_thread import**_
plots/conversation_refresh_times_inv.png _**resolved - driver_author import**_
plots/conversation_refresh_times.png _**resolved - driver_author import**_
plots/daily-message-activity-timeline.html _**resolved -driver_thread import**_
plots/weekly-message-activity-timeline.html _**resolved - driver_thread import**_
plots/monthly-message-activity-timeline.html _**resolved-driver_thread import**_
plots/yearly-message-activity-timeline.html _**resolved-driver_thread import**_
plots/hyperedge_distribution.png _**resolved-driver_thread import**_
plots/response_time_inv.png _**resolved-driver_thread import**_
plots/response_time.png _**resolved-driver_thread import**_
plots/thread_length_inv.png _**resolved-driver_thread import**_
plots/thread_length.png _**resolved-driver_thread import**_

	 

**Matching** :
author_keyword_digest.txt
curve_fit/*
json/*
tables/author_ranking.csv
tables/author_thread_participation.csv
tables/graph_edges.csv
tables/graph_nodes.csv
tables/hyperedge_distribution.csv
tables/wh_table_authors.csv

**Additions**:
community_vertex_clustering.txt
conversation_refresh_times.csv
conversation_refresh_times_inv.png
conversation_refresh_times.png
plots/author_thread_participation.png
vc.pdf
vd.pdf

**Comment by prasadtalasila** [comment]
@yashpungaliya modify code to give proper names to vc.pdf and vd.pdf.

**Comment by prasadtalasila** [comment]
moved to [wiki page](https://github.com/DeveloperCAP/MLCAT/wiki/Reproduction-of-Results)
